version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
